# .github/workflows/build-desktop-app.yml

name: Build Desktop App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a versão do Node.js que você está usando (ou a mais recente LTS)

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Use uma versão de Python que você sabe que funciona bem (ex: 3.10 ou 3.11)

      - name: Install root dependencies
        run: npm install

      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Install backend Python dependencies
        run: |
          python -m venv backend/venv
          source backend/venv/bin/activate
          pip install -r backend/requirements.txt
          pip install pyinstaller
          deactive

      - name: Build Frontend (Next.js)
        run: npm run build:frontend
        env:
          NEXT_PUBLIC_API_URL: 'http://localhost:8000'

      - name: Build Backend (PyInstaller)
        run: npm run build:backend 
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Install Electron Builder dependencies
        run: npm install electron-builder --prefix .

      - name: Package Electron App
        run: npm run package
        env:
          BUILD_ENV: 'production' 

      - name: Upload artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: RevisuApp-windows
          path: release/*.exe

      - name: Upload artifacts (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: RevisuApp-linux
          path: release/*.AppImage

